// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pqievwbfrbiqhvdyalrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxaWV2d2JmcmJpcWh2ZHlhbHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDQ1MDEsImV4cCI6MjA3NzA4MDUwMX0.e0Pc2M9c-NCwkWxM8ssJhv-ANFojJipeQY4W9UPgg4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);